### PR TITLE
replaced the CFShow with printf

### PR DESCRIPTION
**Pull request by Incont**

### CODE REVIEW

**Comment by Incont** [comment]
fixed Bug: stderr incorrect #139
fixed Minor bug: incorrect log #138

**Comment by Incont** [comment]
It is better to replace <code>printf(text); exit(1); </code> with <code>on_error(text)</code>

**Comment by shazron** [comment]
I don't agree with removing CFShow with printf. Is this fixing a real issue?

**Comment by shazron** [comment]
Just saw #139. I think a better change would be changing CFShow to NSLog, so logs go to stdout instead.

**Pull request closed without merging**
