### PR TITLE
Add --mkdir and --rm options

### PR DESCRIPTION
**Pull request by luser**
Just a pair of useful utility options for creating directories and removing files. `--rm` doesn't handle removing non-empty directories currently. It wouldn't be that hard to add, you'd just have to iterate over the contents and remove them all if the call to `AFCRemovePath` fails. Presumably you'd want this to be an option, like `rm -r`.

### CODE REVIEW

**Comment by shazron** [comment]
Thanks! Could you add example usage in the README.md if you don't mind?
I'm assuming this functionality is for creating/removing files in the app's sandbox only?

**Comment by luser** [comment]
Yes, it only works to upload files to the sandbox. I'll submit a PR for a README update, sorry for missing that!

**Comment by mikelupo** [comment]
I'm curious, will this support the idea of removing all of a filetype (i.e.*.jpg)? or do I need to know the exact filename before issuing the rm command?
Thanks!!

**Comment by luser** [comment]
It only supports exact filenames currently. I'm not sure how hard glob matching would be.

**Pull request merged**
