### PR TITLE
Phonegap/ios deploy

### PR DESCRIPTION
**Pull request by senthilmanick**
Fixed the issue when iOS devices with japanese locale are connected, iso-deploy -c did not list the name of the device. Take version 1.5.3

### CODE REVIEW

**Comment by shazron** [comment]
Thanks. Unfortunately github is complaining that it can't be auto merged.

**Comment by senthilmanick** [comment]
Merged and you should be able to merge now.
Take version 1.5.3

**Comment by shazron** [comment]
Actually, Github is still complaining (merge conflicts).

**Comment by senthilmanick** [comment]
I merged and when I ask for any pull request, it says everything is fine. 
Can you do a manual merge? You shouldn't see any conflicts there. 
In fact you can take my version. 
-Senthil 

----- Original Message -----

**Comment by senthilmanick** [comment]
Were you able to merge? 
I confirmed with a Japanese user that he was able to build and download 
-Senthil 

----- Original Message -----

**Comment by shazron** [comment]
Thanks - I haven't had time to look at this, I'll take a look Sunday night or Monday. Will definitely get to it then for sure.

**Comment by shazron** [comment]
Github is correct.

From this repo's master branch I tried:
```
$ git pull https://github.com/senthilmanick/ios-deploy.git phonegap/ios-deploy
From https://github.com/senthilmanick/ios-deploy
 * branch            phonegap/ios-deploy -> FETCH_HEAD
Auto-merging ios-deploy.c
CONFLICT (content): Merge conflict in ios-deploy.c
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by senthilmanick** [comment]
Let me do the merge again 
And post a pull request 

----- Original Message -----

**Pull request merged**
