### PR TITLE
add --nolldb (-N): start debugserver without lldb

### PR DESCRIPTION
**Pull request by 0xItx**
Comes in hadny when one wishes to attach with an external debugserver client (e.g. a custom lldb or IDA)

### CODE REVIEW

**Comment by shazron** [comment]
Thanks for the PR! Can you add an example under the Examples section in the README on how to use this (point a link perhaps to an example use case).

**Comment by 0xItx** [comment]
@shazron - I've added an example command-line usage

**Comment by LinusU** [comment]
@shazron It seems like this was added to the changelog, and to the readme, but it doesn't seem to be included with the 1.9.2 release:

```text
$ ios-deploy --version
1.9.2

$ ios-deploy --nolldb --port 6666 --bundle build/Release-iphoneos/MyAwesomeApp.app
ios-deploy: unrecognized option `--nolldb'
```

**Comment by LinusU** [comment]
Hmm, it seems like this merge commit accidentally removed it: 3656c1dc464c04772c5521384dc815c06fdf5742

**Comment by LinusU** [comment]
Added it back here: #331

**Pull request merged**
