### PR TITLE
Bring list of error messages up-to-date.

### PR DESCRIPTION
**Pull request by jakepetroules**
Automatically generated using MobileDevice.framework private APIs using [a tool I hacked together](https://gist.github.com/jakepetroules/c7d621e748409b01ad7a83384f2fb7f7).

Xcode 7.3.1 and OS X 10.11.5.

### CODE REVIEW

**Comment by shazron** [comment]
Thanks! Once the Travis CI checks pass, I'll pull this in.

**Comment by jakepetroules** [comment]
These lists were automatically generated using [a tool I hacked together](https://gist.github.com/jakepetroules/c7d621e748409b01ad7a83384f2fb7f7).

**Comment by akofman** [comment]
Excellent !

**Comment by jakepetroules** [comment]
I'd recommend just using the APIs directly rather than hardcoding the error strings, so that we don't have to keep updating it. We're [making that change in Qt Creator 4.1](https://codereview.qt-project.org/#/c/160005/) as well. See that or my linked tool for guidance. I don't have a lot of time to spend on this so I'll leave that exercise to someone else. :)

**Pull request merged**
